def cloneRepo(){
    return {
        dir("${env.WORKSPACE}/${BUILD_NUMBER}"){
            git url:'https://github.com/leonidesfernando/perf-tests', branch: 'main'
        }   
    }
}

def createDir(){
    return {
        bat(/mkdir ${env.WORKSPACE}\${BUILD_NUMBER}/)
    }
}

def configuringLighthouse() {
    return {
        dir("${env.WORKSPACE}/${BUILD_NUMBER}/lighthouse"){
            bat(/npm install/)
        }
    }
}

def runningLighthouse(){
    return {
        dir("${env.WORKSPACE}/${BUILD_NUMBER}/lighthouse"){
            bat(/node shopizer.js/)
        }
    }
}

def publishResults(){
    return {
        dir("${env.WORKSPACE}/${BUILD_NUMBER}/lighthouse"){
            archiveArtifacts artifacts: 'report.json', fingerprint: true
            archiveArtifacts artifacts: 'user-flow.report.html', fingerprint: true
            lighthouseReport file: 'report.json', name: 'My Report'
        }
    }
}

def callFunction(functions){
    return {
        functions.each { func  ->
            func.value.call()
        }
    }
}

def map = [
	"Configuring" :[
		func: createDir()
	],
    "Cloning Git repo": [
        func: cloneRepo()
    ],
    "Configuring Lighthouse": [
        func: configuringLighthouse()
    ],
    "Running Lighthouse": [
        func: runningLighthouse()
    ],
    "Publishing results": [
        func:  publishResults()
    ]
];


pipeline{
    agent any
    parameters {
        choice(name: "REPETITIONS", choices: ["1", "3", "5", "10"], description: "Number of repetitions")
    }
    stages{

        stage("Looping"){
            steps{
                script{
                    def count = Integer.valueOf("${params.REPETITIONS}".toString())
                    for(int i = 1; i <= count; i++){
                        echo "couting"
                        /*stage("Running"){
                            bat(/mkdir ${env.WORKSPACE}\${BUILD_NUMBER}\${i}/)
                            bat(/mkdir ${env.WORKSPACE}\${BUILD_NUMBER}\${i}\lighthouse/)
                            dir("${env.WORKSPACE}/${BUILD_NUMBER}/${i}/lighthouse"){
                                bat(/node shopizer.js/)
                            }
                        }*/
                        //
        stage('Configuring') {
            steps{
            bat(/mkdir ${env.WORKSPACE}\${BUILD_NUMBER}\{i}/)
            }
        }
        stage("Clonning git repo"){
            steps{
                dir("${env.WORKSPACE}/${BUILD_NUMBER}/{i}"){
                    git url:'https://github.com/leonidesfernando/perf-tests', branch: 'main'
                }
            }
        }
        stage("Configuring Lighthouse"){
            steps{
                dir("${env.WORKSPACE}/${BUILD_NUMBER}/{i}/lighthouse"){
                    bat(/npm install/)
                }
            }
        }
                    }
                 }
            }
        }
    }
}



/*
pipeline{
    agent any
    parameters {
        choice(name: "REPEAT", choices: ["1", "3", "5", "10"], description: "Number of repetitions")
    }
    stages{
        stage("Loop"){
            steps{
                script{
                    map.each { entry  ->
                        stage(entry.key){
                            callFunction(entry.value).call()
                        };
                    }                    
                }
            }
        }
    }
}*/

/*
node {          
	map.each { entry  ->
	   stage(entry.key){
		   callFunction(entry.value).call()
	   };
	}
}*/
